name: Create Release

on:
  push:
    tags:
      - '*'
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.2
    - name: Read/Write Properties File
      uses: kurt-code/gha-properties@v0.0.2
      id: read-properties
      with:
        operation: 'read'
        file-path: 'src/main/resources/application.properties'
        keys: |
          'trivysummary.version'
    - name: "Get the Read properties"
      run: |
          echo "version: ${{ steps.read-properties.outputs.trivysummary_version }}"
    - name: "Create Release"
      id: create_release
      uses: softprops/action-gh-release@v2.0.2
      if: startsWith(github.ref, 'refs/tags/') && endsWith(github.ref, steps.read-properties.outputs.trivysummary_version)
      with:
        tag_name: ${{ steps.read-properties.outputs.trivysummary_version }}
        name: Release ${{ steps.read-properties.outputs.trivysummary_version }}
        body_path: CHANGELOG.txt
        files: TrivySummary-${{ steps.read-properties.outputs.trivysummary_version }}.zip
