name: Create Release

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Release
      uses: docker://antonyurchenko/git-release:v6.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.MAVENREPO_TOKEN }}
      with:
        args: build/distributions/*.zip
