name: Java CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5.0.0
    - name: Set up JDK 21
      uses: actions/setup-java@v5.0.0
      with:
        java-version: 21
        distribution: corretto
    - name: Read/Write Properties File
      uses: kurt-code/gha-properties@v0.0.2
      id: read-properties
      with:
        operation: 'read'
        file-path: 'src/main/resources/application.properties'
        keys: 'trivysummary.version'
    - name: Get the Read properties
      run: |
        echo "version: ${{ steps.read-properties.outputs.trivysummary_version }}"
        echo "github.ref: ${{ github.ref }}"
    - name: Test with Gradle
      run: gradle test --warning-mode all
    - name: Build with Gradle
      run: gradle distZip --warning-mode all
    - name: Publish with Gradle
      if: endsWith(steps.read-properties.outputs.trivysummary_version, '-SNAPSHOT') || (startsWith(github.ref, 'refs/tags/') && endsWith(github.ref, steps.read-properties.outputs.trivysummary_version))
      run: gradle publish -Pmvnpub.user="${{ secrets.MAVENREPO_USER }}" -Pmvnpub.key="${{ secrets.MAVENREPO_TOKEN }}" --warning-mode all
    - name: "Create Release"
      id: create_release
      uses: softprops/action-gh-release@v2.3.3
      if: startsWith(github.ref, 'refs/tags/') && endsWith(github.ref, steps.read-properties.outputs.trivysummary_version)
      with:
        tag_name: ${{ steps.read-properties.outputs.trivysummary_version }}
        name: Release ${{ steps.read-properties.outputs.trivysummary_version }}
        body_path: CHANGELOG.txt
        token: ${{ secrets.MAVENREPO_TOKEN }}
        files: build/distributions/trivysummary-${{ steps.read-properties.outputs.trivysummary_version }}.zip
