name: Java CI

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.2
    - name: Set up JDK 21
      uses: actions/setup-java@v4.1.0
      with:
        java-version: 21
        distribution: corretto
    - name: Read/Write Properties File
      uses: kurt-code/gha-properties@v0.0.2
      id: read-properties
      with:
        operation: 'read'
        file-path: 'src/main/resources/application.properties'
        keys: 'trivysummary.version'
    - name: Get the Read properties
      run: |
        echo "version: ${{ steps.read-properties.outputs.trivysummary_version }}"
    - name: Build with Gradle
      run: gradle distZip publish -Pmvnpub.user="${{ secrets.MAVENREPO_USER }}" -Pmvnpub.key="${{ secrets.MAVENREPO_TOKEN }}" --warning-mode all
 
