name: Java CI

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.2
    - name: Set up JDK 21
      uses: actions/setup-java@v4.1.0
      with:
        java-version: 21
        distribution: corretto
    - name: Build with Gradle
      run: gradle distZip publish -Pmvnpub.user="${{ secrets.MAVENREPO_USER }}" -Pmvnpub.key="${{ secrets.MAVENREPO_TOKEN }}" --warning-mode all
    - name: Read/Write Properties File
      uses: kurt-code/gha-properties@v0.0.2
      id: read-properties
      with:
        operation: 'read'
        file-path: 'path/to/properties/file'
        keys: 'trivysummary.version'
    - name: Get the Read properties
      run: |
        echo "version: ${{ steps.read-properties.outputs.trivysummary.version }}"
    - name: version
      run: echo "::set-output name=version::$(./bin/trivysummary --version)"
      id: version
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}      
